---
- name: install repository remi
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: install php
  yum: enablerepo=remi,remi-php73 name={{ item }} state=present
  with_items:
    - php
    - php-mbstring
    - php-xml
    - php-xmlrpc
    - php-gd
    - php-pdo
    - php-pecl-mcrypt
    - php-mysqlnd
    - php-pecl-mysql



